#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mox
Version  : 0.5.3
Release  : 9
URL      : https://pypi.python.org/packages/source/m/mox/mox-0.5.3.tar.gz
Source0  : https://pypi.python.org/packages/source/m/mox/mox-0.5.3.tar.gz
Summary  : Mock object framework
Group    : Development/Tools
License  : Apache-2.0
Requires: mox-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
Mox is an open source mock object framework for Python, inspired by
the Java library EasyMock.

%package python
Summary: python components for the mox package.
Group: Default

%description python
python components for the mox package.


%prep
%setup -q -n mox-0.5.3

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
python mox_test.py
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
