#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mox
Version  : 0.5.3
Release  : 17
URL      : http://pypi.debian.net/mox/mox-0.5.3.tar.gz
Source0  : http://pypi.debian.net/mox/mox-0.5.3.tar.gz
Summary  : Mock object framework
Group    : Development/Tools
License  : Apache-2.0
Requires: mox-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Java mock object framework EasyMock.

%package python
Summary: python components for the mox package.
Group: Default

%description python
python components for the mox package.


%prep
%setup -q -n mox-0.5.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503121645
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python mox_test.py
%install
export SOURCE_DATE_EPOCH=1503121645
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
